### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aliosmanyuksel** [m4ll0k/WAScan#1]
c:\projects\Spaghetti>python spaghetti.py
Traceback (most recent call last):
  File "spaghetti.py", line 12, in <module>
    from modules.discovery import All
  File "c:\projects\Spaghetti\modules\discovery\All.py", line 16, in <module>
    import Captcha
  File "c:\projects\Spaghetti\modules\discovery\Captcha.py", line 13, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by m4ll0k** [comment]
pip install BeautifulSoup

**Comment by cclauss** [comment]
Would it be possible to step up to BeautifulSoup4 or is there something special about bs3?

**Comment by aliosmanyuksel** [comment]
Yeah, it solved my problem. @m4ll0k

**Comment by codingo** [comment]
@m4ll0k Why the reopen given that it's a dependency?
