### ISSUE TITLE
If spaghetti is added to the path, error occurs

### ISSUE THREAD

**Issue by phlogistic** [m4ll0k/WAScan#30]
Scans can only be run in the directory that spaghetti was cloned into. 

If spaghetti.py is added to a machine's path, and an attempt is made to scan, the following error occurs

    [i] Checking common files...
    Traceback (most recent call last):
      File "/jjjj/git/Spaghetti/spaghetti.py", line 123, in <module>
        main = Spaghetti().main(sys.argv[1:])
      File "/jjjj/git/Spaghetti/spaghetti.py", line 81, in main
        agent,proxy,redir,time,self.url,cookie)
      File "/jjjj/git/Spaghetti/utils/manager.py", line 44, in bruteforce
        cookie = cookie
      File "/jjjj/git/Spaghetti/modules/discovery/brute/brute.py", line 38, in run
        cookie = self.cookie
      File "/jjjj/git/Spaghetti/modules/discovery/brute/file.py", line 36, in run
        db = open('data/cfile.txt','rb')
    IOError: [Errno 2] No such file or directory: 'data/cfile.txt'

**Comment by root-lo0p** [comment]
The following bash one-liner (ran from /jjjj/git/Spaghetti/) should serve you well until this is addressed:

find -type f | xargs sed -i "s/db = open('/db = open('\/jjjj\/git\/Spaghetti\//g" && find -type f | xargs sed -i "s/db1 = open('/db1 = open('\/jjjj\/git\/Spaghetti\//g"

Best,
rootlo0p
