### ISSUE TITLE
IndexError: list index out of range   

### ISSUE THREAD

**Issue by Kaicastledine** [m4ll0k/WAScan#33]
Running on OSX high seria 

**Command run** 
`python wascan.py --verbose --url http://www.WESBITE.co.uk --scan 1`

**Print out** 
```
KCMP:wascan kaic$  python wascan.py --verbose --url http://www.WESBITE.co.uk --scan 1
__________________________________________________
 ________ _______ _______                   
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.1.0
      WAScan - Web Application Scanner      
              C0d3n4m3: Kus-Kus              
           Momo Outaadi (m4ll0k)            
__________________________________________________

[+] URL: http://www.WESBITE.co.uk
[+] Starting: 28/02/2018 at 13:55:10

[i] Starting attack module...
Traceback (most recent call last):
  File "wascan.py", line 111, in <module>
    wascan().main()
  File "wascan.py", line 87, in main
    Attacks(kwargs,url,kwargs['data'])
  File "/Users/kaic/Pentest/wascan/lib/handler/attacks.py", line 30, in Attacks
    blindsqli(kwargs,url,data).run()
  File "/Users/kaic/Pentest/wascan/plugins/attacks/blindsqli.py", line 55, in run
    for url in urls.run():
  File "/Users/kaic/Pentest/wascan/lib/utils/params.py", line 75, in run
    self.get()
  File "/Users/kaic/Pentest/wascan/lib/utils/params.py", line 55, in get
    params = self.url.split("?")[1].split("&")
IndexError: list index out of range
```

**Comment by s0i37** [comment]
Hello. I have the same error in attack-mode:
./wascan.py --url http://testphp.vulnweb.com/ --scan 1 --verbose.
But if I "try-catch" all problem lines I will have no any results...
By the way, "wascan" seems very "similar" on w3af. Is it fully rewrited scanner or you use engine one?

**Comment by shreyaspg** [comment]
Hey so it's not a code error, the logic of code expects the post data , I'd recommend using something like this

python wascan.py --url https://sometargetwebsite.com/loginpath -d "username=something&password=else" --scan 1

the data is passed using the -d arg, so go inspect the name of the form fields on the target site ,in my case it was username and password.
