### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Boris519** [m4ll0k/WAScan#35]
[i] Starting attack module...
Traceback (most recent call last):
  File "wascan.py", line 111, in <module>
    wascan().main()
  File "wascan.py", line 103, in main
    FullScan(kwargs,u,kwargs['data'])
  File "/root/WAScan/lib/handler/fullscan.py", line 19, in FullScan
    Attacks(kwargs,url,data)
  File "/root/WAScan/lib/handler/attacks.py", line 30, in Attacks
    blindsqli(kwargs,url,data).run()
  File "/root/WAScan/plugins/attacks/blindsqli.py", line 55, in run
    for url in urls.run():
  File "/root/WAScan/lib/utils/params.py", line 71, in run
    self.get()
  File "/root/WAScan/lib/utils/params.py", line 57, in get
    ppayload = param.replace(param.split("=")[1],param.split('=')[1]+self.payload)
IndexError: list index out of range

**Comment by Boris519** [comment]
`Exception in thread Thread-27 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/root/WAScan/plugins/brute/adminpanel.py", line 62, in run
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 333, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable`

**Comment by m4ll0k** [comment]
thank's **Boris519**
