### ISSUE TITLE
error  bug...

### ISSUE THREAD

**Issue by 1522402210** [m4ll0k/WAScan#40]
[i] Starting fingerprint target...
Exception: ''
[i] Starting crawler...
Traceback (most recent call last):
  File "wascan.py", line 111, in <module>
    wascan().main()
  File "wascan.py", line 98, in main
    for u in Crawler().run(kwargs,url,kwargs['data']):
  File "/Users/WAScan/lib/handler/crawler.py", line 19, in run
    for k in SCrawler(kwargs, url, data).run():
  File "/Users/WAScan/lib/request/crawler.py", line 39, in run
    resp = self.Send(url=self.url,data=self.data)
  File "/Users/WAScan/lib/request/request.py", line 116, in Send
    resp = urllib2.urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by maybecoward** [comment]
Can you tell me how to reslove the question?
