### ISSUE TITLE
Exception when bruteforcing admin panel

### ISSUE THREAD

**Issue by LockeLamora** [m4ll0k/WAScan#46]
Last [i] is "Bruteforce admin panel"

python3 wascan.py --url testurlommitted --scan 5

> Exception in thread Thread-27 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/WAScan/plugins/brute/adminpanel.py", line 62, in run
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 333, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by m4ll0k** [comment]
I'm writing another version
