### ISSUE TITLE
timeout parameter doesn't seem to work

### ISSUE THREAD

**Issue by LockeLamora** [m4ll0k/WAScan#47]
call:

python wascan.py --url testurlommitted -t 0.5

> [i] Starting full scan module...
[i] Starting fingerprint target...
Exception: a float is required
[i] Starting crawler...
Traceback (most recent call last):
  File "wascan.py", line 111, in <module>
    wascan().main()
  File "wascan.py", line 98, in main
    for u in Crawler().run(kwargs,url,kwargs['data']):
  File "/opt/WAScan/lib/handler/crawler.py", line 19, in run
    for k in SCrawler(kwargs, url, data).run():
  File "/opt/WAScan/lib/request/crawler.py", line 39, in run
    resp = self.Send(url=self.url,data=self.data)
  File "/opt/WAScan/lib/request/request.py", line 83, in Send
    socket.setdefaulttimeout(timeout)
TypeError: a float is required

**Comment by theInfectedDrake** [comment]
Seems like the parameter `-t` needs to be handled as float `explicitly`.

**Comment by m4ll0k** [comment]
resolved
