### ISSUE TITLE
Error in "wascan.py" line 111

### ISSUE THREAD

**Issue by securiteinfo** [m4ll0k/WAScan#48]
[i] Starting attack module...
Traceback (most recent call last):
  File "wascan.py", line 111, in <module>
    wascan().main()
  File "wascan.py", line 103, in main
    FullScan(kwargs,u,kwargs['data'])
  File "/root/WAScan/lib/handler/fullscan.py", line 19, in FullScan
    Attacks(kwargs,url,data)
  File "/root/WAScan/lib/handler/attacks.py", line 30, in Attacks
    blindsqli(kwargs,url,data).run()
  File "/root/WAScan/plugins/attacks/blindsqli.py", line 55, in run
    for url in urls.run():
  File "/root/WAScan/lib/utils/params.py", line 71, in run
    self.get()
  File "/root/WAScan/lib/utils/params.py", line 57, in get
    ppayload = param.replace(param.split("=")[1],param.split('=')[1]+self.payload)
IndexError: list index out of range

**Comment by theInfectedDrake** [comment]
From the error, it looks like you havent entered a parameter which is the requirement to be supplied as an argument. Mind giving a more detailed information about your command?

**Comment by m4ll0k** [comment]
I'm writing another version
