### ISSUE TITLE
request and timeout issues ...how do i solve this?

### ISSUE THREAD

**Issue by filebe777** [m4ll0k/WAScan#57]
[+] X-Content-Type-Options header missing
[i] Starting crawler...
Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 102, in main
    for u in Crawler().run(kwargs,url,kwargs['data']):
  File "/root/Desktop/wascan/lib/handler/crawler.py", line 19, in run
    for k in SCrawler(kwargs, url, data).run():
  File "/root/Desktop/wascan/lib/request/crawler.py", line 39, in run
    resp = self.Send(url=self.url,data=self.data)
  File "/root/Desktop/wascan/lib/request/request.py", line 123, in Send
    return ResponseObject(resp)
  File "/root/Desktop/wascan/lib/request/request.py", line 136, in __init__
    self.content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.timeout: timed out

**Comment by m4ll0k** [comment]
I'm writing another version

**Comment by filebe777** [comment]
cool... waiting patiently
