### ISSUE TITLE
Crawler Error -  Starting crawler... Traceback (most recent call last):   File "wascan.py", line 118, in <module>

### ISSUE THREAD

**Issue by filebe777** [m4ll0k/WAScan#60]
[i] Starting full scan module...
[i] Starting fingerprint target...
[+] Server: Microsoft-IIS/7.5
[+] Language: ASP.NET
[+] Language: ASP
[+] Cookie without Secure flag set
[+] Cookie without HttpOnly flag set
[+] Session Cookie are valid only on that Path: /
[+] Cookie Header contains multiple cookies
[+] X-XSS-Protection header missing
[+] Clickjacking: X-Frame-Options header missing
[+] Strict-Transport-Security header missing
[+] X-Content-Type-Options header missing
[i] Starting crawler...
Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 102, in main
    for u in Crawler().run(kwargs,url,kwargs['data']):
  File "/root/Desktop/wascan/lib/handler/crawler.py", line 19, in run
    for k in SCrawler(kwargs, url, data).run():
  File "/root/Desktop/wascan/lib/request/crawler.py", line 39, in run
    resp = self.Send(url=self.url,data=self.data)
  File "/root/Desktop/wascan/lib/request/request.py", line 123, in Send
    return ResponseObject(resp)
  File "/root/Desktop/wascan/lib/request/request.py", line 136, in __init__
    self.content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.timeout: timed out

**Comment by codingo** [comment]
This looks like an input problem, can you share what flags you used?

**Comment by latikas12** [comment]
same problem

**Comment by m4ll0k** [comment]
Flag? e.g: `python wascan.py -u ....etc`

**Comment by camillegroult** [comment]
Hey all users, 

I think is not about flag, but its working only if you add '?' in your URL. please let me know
