### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by majidmc2** [m4ll0k/WAScan#72]
Hi 
I executed this command after that I got this Error
Command:
`python wascan.py --url http://192.168.1.14 --scan 1`

Error:
`Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 91, in main
    Attacks(kwargs,url,kwargs['data'])
  File "/home/majidmc2/wascan/lib/handler/attacks.py", line 24, in Attacks
    module(kwargs,url,data).run()
  File "/home/majidmc2/wascan/plugins/attacks/xxe.py", line 49, in run
    for url in urls.run():
  File "/home/majidmc2/wascan/lib/utils/params.py", line 41, in run
    self.get()
  File "/home/majidmc2/wascan/lib/utils/params.py", line 21, in get
    params = self.url.split("?")[1].split("&")
IndexError: list index out of range
`

**Comment by Solotov** [comment]
You can solve this bug adding **?** Symbol to your GET request:

`python wascan.py --url http://192.168.1.14/? --scan 1`

[https://repl.it/@SolotovD/WAScan-Get-URL-Bug](https://repl.it/@SolotovD/WAScan-Get-URL-Bug)

Bug source:
`"https://github.com/m4ll0k/WAScan/blob/master/lib/utils/params.py", Line 21`

**Comment by tanaydin** [comment]
please check https://github.com/m4ll0k/WAScan/pull/80
