### ISSUE TITLE
run wascan.py error 

### ISSUE THREAD

**Issue by M0dred** [m4ll0k/WAScan#75]
python -V
Python 2.7.17

uname -a
Linux Kxxxx 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

[i] Starting full scan...
[i] Starting attacks module...
[i] Checking OS Command Injection...
Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 110, in main
    FullScan(kwargs,u,kwargs['data'])
  File "/opt/github/WAScan/lib/handler/fullscan.py", line 19, in FullScan
    Attacks(kwargs,url,data)
  File "/opt/github/WAScan/lib/handler/attacks.py", line 24, in Attacks
    module(kwargs,url,data).run()
  File "/opt/github/WAScan/plugins/attacks/oscommand.py", line 50, in run
    req = self.Send(url=url,method=self.get)
  File "/opt/github/WAScan/lib/request/request.py", line 116, in Send
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1069, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1103, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 940, in putrequest
    self._validate_path(url)
  File "/usr/lib/python2.7/httplib.py", line 1030, in _validate_path
    raise InvalidURL(msg)
httplib.InvalidURL: URL can't contain control characters. '/e/tool/gbook/?bid=1%26echo "edqZLOttvUHRsziyRpTvLxceqmIACw"' (found at least ' ')

**Comment by azamet90** [comment]
same here

**Comment by tanaydin** [comment]
Please check
https://github.com/m4ll0k/WAScan/pull/79
