### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by azamet90** [m4ll0k/WAScan#77]
```
python wascan.py --url http://xxxxx.com/index.php?id=1 --scan 1
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.2.1
      WAScan - Web Application Scanner      
           C0d3n4m3: ATLAS                  
          Momo Outaadi (m4ll0k)             
__________________________________________________

[+] URL: http://xxxxx.com/index.php?id=1
[+] Starting: 27/11/2019 at 17:30:01

[i] Starting attacks module...
[i] Checking OS Command Injection...
Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 91, in main
    Attacks(kwargs,url,kwargs['data'])
  File "/home/azamet/Belgeler/wascan/lib/handler/attacks.py", line 24, in Attacks
    module(kwargs,url,data).run()
  File "/home/azamet/Belgeler/wascan/plugins/attacks/oscommand.py", line 50, in run
    req = self.Send(url=url,method=self.get)
  File "/home/azamet/Belgeler/wascan/lib/request/request.py", line 116, in Send
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1069, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1103, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 940, in putrequest
    self._validate_path(url)
  File "/usr/lib/python2.7/httplib.py", line 1030, in _validate_path
    raise InvalidURL(msg)
httplib.InvalidURL: URL can't contain control characters. '/index.php?id=1%26echo "fMNrpHYaRAFnPJnwtALjUBwEELZUIU"' (found at least ' ')

```

**Comment by tanaydin** [comment]
Please check https://github.com/m4ll0k/WAScan/pull/79
