### ISSUE TITLE
Not Working Good

### ISSUE THREAD

**Issue by Sajibekanti** [m4ll0k/WAScan#9]
In Windows 10 Python 2.7 Not Working 

C:\Users\Sati\Desktop\Bugz>spaghetti.py
Traceback (most recent call last):
  File "C:\Users\Sati\Desktop\Bugz\spaghetti.py", line 12, in <module>
    from modules.discovery import All
  File "C:\Users\Sati\Desktop\Bugz\modules\discovery\All.py", line 16, in <module>
    import Captcha
  File "C:\Users\Sati\Desktop\Bugz\modules\discovery\Captcha.py", line 13, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by m4ll0k** [comment]
`pip install BeautifulSoup `
